dist: trusty
language: node_js
node_js:
  - "0.10"
  - "4.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libprotobuf-dev protobuf-compiler libsqlite3-dev
  - git clone https://github.com/mapbox/tippecanoe.git;cd tippecanoe;make;sudo make install
script: npm install && npm test
