dist: trusty
language: node_js
node_js:
  - "0.10"
  - "4.5"
script: apt-get install -y libprotobuf-dev protobuf-compiler libsqlite3-dev;git clone https://github.com/mapbox/tippecanoe.git;cd tippecanoe;make;make install;cd ..;npm install && npm test
