version: '3'
services:
  redis:
    image: redis:latest

  mtp:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - MTP_HOST=mtp
    links:
      - redis
    ports:
      - '8787:8787'
    command: sleep 1d
